version: "3.7"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./:/app
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
    networks:
      - backend

networks:
  backend:
    driver: bridge
